[project]
name = "airflow-rag-spike"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow==3.1.0",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.9",
    "ruff>=0.13.3",
]
